/*
 * ApuestaTiroCraps.java
 *
 * Created on 27 de julio de 2008, 02:43
 */

package juegocraps.vista;

import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.io.xml.DomDriver;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import juegocraps.entidades.Mesa;
import juegocraps.entidades.MesaConverter;
import juegocraps.entidades.Usuario;
import juegocraps.entidades.UsuarioConverter;
import juegocraps.entidades.VTermConverter;
import juegocraps.entidades.Vterm;
import juegocraps.entidades.apuesta.ApuestaTiroCraps;
import juegocraps.entidades.apuesta.FichaValor;
import juegocraps.entidades.apuesta.OpcionApuesta;
import juegocraps.entidades.apuesta.RespuestaApuestaCraps;
import juegocraps.entidades.tiro.RespuestaTiroCraps;
import juegocraps.entidades.tiro.TiroCraps;

/**
 *
 * @author  Yakko
 */
public class ApuestaTiroCrapsVista extends javax.swing.JFrame {

    /** Creates new form ApuestaTiroCraps */
    public ApuestaTiroCrapsVista() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoApuesta = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonPase = new javax.swing.JRadioButton();
        jRadioButtonVenir = new javax.swing.JRadioButton();
        jRadioButtonCampo = new javax.swing.JRadioButton();
        jRadioButtonNoPase = new javax.swing.JRadioButton();
        jRadioButtonNoVenir = new javax.swing.JRadioButton();
        jRadioButtonAGanar = new javax.swing.JRadioButton();
        jRadioButtonEnContra = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jTextPuntaje = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTextValorFicha = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextCantidad = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTextIdTerminal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextIdGrupo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextMesa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jRadioAceptadoSi = new javax.swing.JRadioButton();
        jRadioAceptadoNo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextTipoJugada = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextDado1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextDado2 = new javax.swing.JTextField();
        jButtonApostar = new javax.swing.JButton();
        jButtonTirar = new javax.swing.JButton();

        TipoApuesta.add(jRadioButtonAGanar);
        TipoApuesta.add(jRadioButtonCampo);
        TipoApuesta.add(jRadioButtonEnContra);
        TipoApuesta.add(jRadioButtonPase);
        TipoApuesta.add(jRadioButtonNoPase);
        TipoApuesta.add(jRadioButtonVenir);
        TipoApuesta.add(jRadioButtonNoVenir);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Apuesta/Tiro Craps");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Apuesta"));

        jRadioButtonPase.setSelected(true);
        jRadioButtonPase.setText("pase");
        jRadioButtonPase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPaseActionPerformed(evt);
            }
        });

        jRadioButtonVenir.setText("venir");

        jRadioButtonCampo.setText("campo");

        jRadioButtonNoPase.setText("no pase");

        jRadioButtonNoVenir.setText("no venir");

        jRadioButtonAGanar.setText("a ganar");

        jRadioButtonEnContra.setText("en contra");

        jLabel9.setText("Puntaje Apostado");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ficha / Valor"));

        jLabel10.setText("Valor Ficha");

        jLabel11.setText("Cantidad");

        jTextCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCantidadActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel11)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jTextCantidad)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jTextValorFicha)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel10)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextValorFicha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel11)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextCantidad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jRadioButtonPase)
                            .add(jRadioButtonVenir)
                            .add(jRadioButtonCampo))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jRadioButtonAGanar)
                            .add(jRadioButtonNoVenir)
                            .add(jRadioButtonNoPase)))
                    .add(jRadioButtonEnContra)
                    .add(jLabel9)
                    .add(jTextPuntaje, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioButtonPase)
                    .add(jRadioButtonNoPase))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioButtonVenir)
                    .add(jRadioButtonNoVenir))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioButtonCampo)
                    .add(jRadioButtonAGanar))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jRadioButtonEnContra)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel9)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextPuntaje, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 30, Short.MAX_VALUE)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Comunes"));

        jLabel1.setText("Id Terminal");

        jLabel4.setText("Grupo");

        jLabel3.setText("Mesa");

        jLabel2.setText("Jugador");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 165, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jTextMesa)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jTextIdGrupo)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jTextIdTerminal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(jLabel1)
                            .add(jLabel4))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jTextIdTerminal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(8, 8, 8)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jTextIdGrupo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jTextMesa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(477, 477, 477))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Respuesta Tiro"));

        jRadioAceptadoSi.setText("Si");
        jRadioAceptadoSi.setEnabled(false);

        jRadioAceptadoNo.setText("No");
        jRadioAceptadoNo.setEnabled(false);

        jLabel5.setText("Aceptado");

        jLabel6.setText("Tipo jugada");

        jLabel7.setText("Dado 1");

        jLabel8.setText("Dado 2");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel6)
                    .add(jTextTipoJugada, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jRadioAceptadoSi)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jRadioAceptadoNo))
                    .add(jLabel5)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTextDado1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextDado2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel8)
                            .add(jLabel7))))
                .add(78, 78, 78))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioAceptadoSi)
                    .add(jRadioAceptadoNo))
                .add(11, 11, 11)
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextTipoJugada, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(jTextDado1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(jTextDado2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(24, 24, 24))
        );

        jButtonApostar.setText("Apostar");
        jButtonApostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApostarActionPerformed(evt);
            }
        });

        jButtonTirar.setText("Tirar");
        jButtonTirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTirarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(78, 78, 78)
                .add(jButtonTirar)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 150, Short.MAX_VALUE)
                .add(jButtonApostar)
                .add(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(13, 13, 13)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 153, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonTirar)
                    .add(jButtonApostar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonApostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApostarActionPerformed
    
    //Estas son las lineas que agregamos
    this.fichas = new ArrayList();
    this.fichas.add(new FichaValor(this.jTextCantidad.getText(), this.jTextValorFicha.getText()));
    
    this.jTextCantidad.setText("");
    this.jTextValorFicha.setText("");
    
    //Si, las lineas de arriba las agregamos
    
    String vTerm = "0000" + this.jTextIdTerminal.getText();
    vTerm = vTerm.substring(vTerm.length()-4, vTerm.length());
    String grupo = "00" + this.jTextIdGrupo.getText();
    grupo = grupo.substring(grupo.length()-2, grupo.length());
    String usuario = this.jTextUsuario.getText();
    String mesa = this.jTextMesa.getText();
    
    String opcion = "";
    
    if (this.jRadioButtonPase.isSelected())
        opcion = "pase";
    else if (this.jRadioButtonNoPase.isSelected()) 
        opcion = "no pase";
    else if (this.jRadioButtonVenir.isSelected())
        opcion = "venir";
    else if (this.jRadioButtonNoVenir.isSelected())
        opcion = "no venir";
    else if (this.jRadioButtonAGanar.isSelected())
        opcion = "a ganar";
    else if (this.jRadioButtonEnContra.isSelected())
        opcion = "en contra";
    else if (this.jRadioButtonCampo.isSelected())
        opcion = "campo";
    
    
    ApuestaTiroCraps apuesta = new ApuestaTiroCraps(
                                        new Vterm(vTerm), 
                                        new Usuario(usuario), 
                                        new Mesa(mesa), 
                                        new OpcionApuesta(opcion, this.jTextPuntaje.getText())
                                        );
    
    apuesta.setValorApuesta(this.fichas);
    
    XStream xstream = new XStream();

    xstream.alias("apuestaCraps", ApuestaTiroCraps.class);
    
    xstream.useAttributeFor(ApuestaTiroCraps.class, "vTerm");
    xstream.registerConverter(new VTermConverter());

    xstream.useAttributeFor(ApuestaTiroCraps.class, "usuario");
    xstream.registerConverter(new UsuarioConverter());

    xstream.useAttributeFor(ApuestaTiroCraps.class, "mesa");
    xstream.registerConverter(new MesaConverter());

    xstream.alias("fichaValor", FichaValor.class);
    
    
    String xml = xstream.toXML(apuesta);
    xml = "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n" + xml;
    //System.out.println(xml);

    FileWriter file;
    try {
    file = new FileWriter("/Temp/Servidor/apuestaCraps" + grupo + vTerm + ".xml");
    file.write(xml);
    file.close();

    } catch (IOException ex) {
       System.err.println("Error en generacion archivo de tiro");
    } 
    
    String archivo = "/Temp/respuestaApuestaCraps" + grupo + vTerm + ".xml";
    while (!(new File(archivo)).exists());
  
    StringBuffer buff = new StringBuffer();
    
    try {
        FileReader fileR = new FileReader(archivo);
    
        fileR.read();

        int c;
        while ((c = fileR.read()) != -1) {
            buff.append(Character.toChars(c)[0]);
        }
        
        fileR.close();
        
        while (!(new File(archivo)).delete());
        
    } catch (IOException ex) {
        System.err.println("Error en lectura respuesta de tiro");
    }
    
    String xml2 = buff.toString();
    
    xml2 = xml2.substring(xml2.indexOf("?>") + 3);
    
    //System.out.println(xml2);
      
    XStream xstream1 = new XStream(new DomDriver());
    
    xstream1.alias("apuestaCraps", RespuestaApuestaCraps.class);
    xstream1.useAttributeFor(RespuestaApuestaCraps.class, "vTerm");
    xstream1.registerConverter(new VTermConverter());

    xstream1.useAttributeFor(RespuestaApuestaCraps.class, "usuario");
    xstream1.registerConverter(new UsuarioConverter());

    xstream1.useAttributeFor(RespuestaApuestaCraps.class, "mesa");
    xstream1.registerConverter(new MesaConverter());

    RespuestaApuestaCraps respuesta = (RespuestaApuestaCraps)xstream1.fromXML(xml2);
    
    ApuestaAceptada vista = new ApuestaAceptada();
    
    vista.setJTextSioNo(respuesta.getAceptado());
    
    vista.setVisible(true);
    
}//GEN-LAST:event_jButtonApostarActionPerformed

private void jRadioButtonPaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPaseActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jRadioButtonPaseActionPerformed

private void jTextCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCantidadActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextCantidadActionPerformed

private void jButtonTirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTirarActionPerformed

    String vTerm = "0000" + this.jTextIdTerminal.getText();
    vTerm = vTerm.substring(vTerm.length()-4, vTerm.length());
    String grupo = "00" + this.jTextIdGrupo.getText();
    grupo = grupo.substring(grupo.length()-2, grupo.length());
    String usuario = this.jTextUsuario.getText();
    String mesa = this.jTextMesa.getText();

    TiroCraps tiro = new TiroCraps(new Vterm(vTerm), new Usuario(usuario), new Mesa(mesa));
    XStream xstream = new XStream();

    xstream.alias("tiroCraps", TiroCraps.class);
    xstream.useAttributeFor(TiroCraps.class, "vTerm");
    xstream.registerConverter(new VTermConverter());

    xstream.useAttributeFor(TiroCraps.class, "usuario");
    xstream.registerConverter(new UsuarioConverter());

    xstream.useAttributeFor(TiroCraps.class, "mesa");
    xstream.registerConverter(new MesaConverter());


    String xml = xstream.toXML(tiro);
    xml = "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n" + xml;
    //System.out.println(xml);

    FileWriter file;
    try {
    file = new FileWriter("/Temp/Servidor/tiroCraps" + grupo + vTerm + ".xml");
    file.write(xml);
    file.close();

    } catch (IOException ex) {
       System.err.println("Error en generacion archivo de tiro");
    } 
    String archivo = "/Temp/respuestaTiroCraps" + grupo + vTerm + ".xml";
    while (!(new File(archivo)).exists());
  
    StringBuffer buff = new StringBuffer();
    
    try {
        FileReader fileR = new FileReader(archivo);
    
        fileR.read();

        int c;
        while ((c = fileR.read()) != -1) {
            buff.append(Character.toChars(c)[0]);
        }
        
        fileR.close();
        
        while (!(new File(archivo)).delete());
        
    } catch (IOException ex) {
        System.err.println("Error en lectura respuesta de tiro");
    }
    
    String xml2 = buff.toString();
    
    xml2 = xml2.substring(xml2.indexOf("?>") + 3);
    
    //System.out.println(xml2);
      
    XStream xstream1 = new XStream(new DomDriver());
    
    xstream1.alias("tiroCraps", RespuestaTiroCraps.class);
    xstream1.useAttributeFor(RespuestaTiroCraps.class, "vTerm");
    xstream1.registerConverter(new VTermConverter());

    xstream1.useAttributeFor(RespuestaTiroCraps.class, "usuario");
    xstream1.registerConverter(new UsuarioConverter());

    xstream1.useAttributeFor(RespuestaTiroCraps.class, "mesa");
    xstream1.registerConverter(new MesaConverter());

    RespuestaTiroCraps respuesta = (RespuestaTiroCraps)xstream1.fromXML(xml2);
    
    if ("si".equals(respuesta.getAceptado())) {
        this.jRadioAceptadoSi.setSelected(true);
        this.jRadioAceptadoNo.setSelected(false);
    } else {
        this.jRadioAceptadoSi.setSelected(false);
        this.jRadioAceptadoNo.setSelected(true);
    }
    
    this.jTextTipoJugada.setText(respuesta.getTipoJugada());
    
    this.jTextDado1.setText(respuesta.getResultado().getDado1());
    this.jTextDado2.setText(respuesta.getResultado().getDado2());
 
    //Esta linea la comentamos y la agregamos en el boton de apostar
    //Suponemos que limpiaba la lista de apuestas qu edespues escribe
//    this.fichas = new ArrayList();
    
}//GEN-LAST:event_jButtonTirarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApuestaTiroCrapsVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup TipoApuesta;
    private javax.swing.JButton jButtonApostar;
    private javax.swing.JButton jButtonTirar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioAceptadoNo;
    private javax.swing.JRadioButton jRadioAceptadoSi;
    private javax.swing.JRadioButton jRadioButtonAGanar;
    private javax.swing.JRadioButton jRadioButtonCampo;
    private javax.swing.JRadioButton jRadioButtonEnContra;
    private javax.swing.JRadioButton jRadioButtonNoPase;
    private javax.swing.JRadioButton jRadioButtonNoVenir;
    private javax.swing.JRadioButton jRadioButtonPase;
    private javax.swing.JRadioButton jRadioButtonVenir;
    private javax.swing.JTextField jTextCantidad;
    private javax.swing.JTextField jTextDado1;
    private javax.swing.JTextField jTextDado2;
    private javax.swing.JTextField jTextIdGrupo;
    private javax.swing.JTextField jTextIdTerminal;
    private javax.swing.JTextField jTextMesa;
    private javax.swing.JTextField jTextPuntaje;
    private javax.swing.JTextField jTextTipoJugada;
    private javax.swing.JTextField jTextUsuario;
    private javax.swing.JTextField jTextValorFicha;
    // End of variables declaration//GEN-END:variables
    private List fichas = new ArrayList();

}
