/*
 * Ingresado.java
 *
 * Created on 4 de julio de 2008, 08:24
 */

package tvirtualcasino;

import com.thoughtworks.xstream.XStream;

import com.thoughtworks.xstream.io.xml.DomDriver;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JTextField;
import tvirtualcasino.entidades.entidadesEstadoCasino.EstadoCasino;

import tvirtualcasino.entidades.UsuarioConverter;
import tvirtualcasino.entidades.VTermConverter;
import tvirtualcasino.entidades.Usuario;
import tvirtualcasino.entidades.Vterm;
import tvirtualcasino.entidades.entidadesEstadoCasino.Juego;
import tvirtualcasino.entidades.entidadesEstadoCasino.Juegos.Craps;
import tvirtualcasino.entidades.entidadesEstadoCasino.Juegos.IdConverter;
import tvirtualcasino.entidades.entidadesEstadoCasino.Juegos.MesaCraps;
import tvirtualcasino.entidades.entidadesEstadoCasino.Juegos.Tragamonedas;
import tvirtualcasino.entidades.entidadesEstadoCasino.Jugador;
import tvirtualcasino.entidades.entidadesEstadoCasino.JugadorConverter;
import tvirtualcasino.entidades.entidadesEstadoCasino.Observador;
import tvirtualcasino.entidades.entidadesEstadoCasino.ObservadorConverter;
import tvirtualcasino.entidades.entidadesEstadoCasino.PozosCasino;
import tvirtualcasino.entidades.entidadesEstadoCasino.RespuestaEstadoCasino;
import tvirtualcasino.entidades.entidadesSalida.RespuestaSalidaCasino;
import tvirtualcasino.entidades.entidadesSalida.SalidaCasino;

/**
 *
 * @author  iiacobac
 */
public class Ingresado extends javax.swing.JFrame {

    /** Creates new form Ingresado */
    public Ingresado() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListJugadores = new javax.swing.JList();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListObservadores = new javax.swing.JList();
        jPanel6 = new javax.swing.JPanel();
        jTextPozoProgresivo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboMesasTraga = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jButtonVerDetalleMesaTr = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jComboMesasCraps = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jButtonVerDetalleMesaCraps = new javax.swing.JButton();
        jButtonEstado = new javax.swing.JButton();
        jButtonSalida = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jRadioButtonJugador = new javax.swing.JRadioButton();
        jRadioButtonObservador = new javax.swing.JRadioButton();
        jTextSaldo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListFichas = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jTextMotivoAceptacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingreso");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado Casino"));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Jugadores"));

        jScrollPane2.setViewportView(jListJugadores);

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Observadores"));

        jScrollPane3.setViewportView(jListObservadores);

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Mesas Tragamonedas"));

        jTextPozoProgresivo.setMaximumSize(new java.awt.Dimension(59, 20));
        jTextPozoProgresivo.setMinimumSize(new java.awt.Dimension(59, 20));
        jTextPozoProgresivo.setPreferredSize(new java.awt.Dimension(59, 20));

        jLabel4.setText("Pozo Progresivo");

        jComboMesasTraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMesasTragaActionPerformed(evt);
            }
        });

        jLabel5.setText("Mesas");

        jButtonVerDetalleMesaTr.setText("Ver Detalle Mesa");
        jButtonVerDetalleMesaTr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerDetalleMesaTrActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(jTextPozoProgresivo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel4))
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jComboMesasTraga, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jButtonVerDetalleMesaTr, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel5)))
                .add(31, 31, 31))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextPozoProgresivo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .add(18, 18, 18)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboMesasTraga, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5))
                .add(18, 18, 18)
                .add(jButtonVerDetalleMesaTr)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Mesas Craps"));

        jComboMesasCraps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMesasCrapsActionPerformed(evt);
            }
        });

        jLabel6.setText("Mesas");

        jButtonVerDetalleMesaCraps.setText("Ver Detalle Mesa");
        jButtonVerDetalleMesaCraps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerDetalleMesaCrapsActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel7Layout = new org.jdesktop.layout.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel7Layout.createSequentialGroup()
                        .add(jComboMesasCraps, 0, 121, Short.MAX_VALUE)
                        .add(30, 30, 30))
                    .add(jPanel7Layout.createSequentialGroup()
                        .add(jLabel6)
                        .addContainerGap(121, Short.MAX_VALUE))
                    .add(jPanel7Layout.createSequentialGroup()
                        .add(jButtonVerDetalleMesaCraps)
                        .addContainerGap(36, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .add(13, 13, 13)
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jComboMesasCraps, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonVerDetalleMesaCraps)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButtonEstado.setText("Pedir Estado");
        jButtonEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEstadoActionPerformed(evt);
            }
        });

        jButtonSalida.setText("Salida");
        jButtonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalidaActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado Jugador"));

        jRadioButtonJugador.setText("Jugador");
        jRadioButtonJugador.setEnabled(false);
        jRadioButtonJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJugadorActionPerformed(evt);
            }
        });

        jRadioButtonObservador.setText("Observador");
        jRadioButtonObservador.setEnabled(false);

        jTextSaldo.setEditable(false);
        jTextSaldo.setMaximumSize(new java.awt.Dimension(59, 20));
        jTextSaldo.setMinimumSize(new java.awt.Dimension(59, 20));
        jTextSaldo.setOpaque(false);
        jTextSaldo.setPreferredSize(new java.awt.Dimension(59, 20));

        jLabel1.setText("Saldo");

        jTextUsuario.setEditable(false);
        jTextUsuario.setMaximumSize(new java.awt.Dimension(100, 20));
        jTextUsuario.setMinimumSize(new java.awt.Dimension(100, 20));
        jTextUsuario.setPreferredSize(new java.awt.Dimension(100, 20));
        jTextUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUsuarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre Usuario");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Fichas habilitadas")));

        jScrollPane1.setViewportView(jListFichas);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        jLabel3.setText("Motivo");

        jTextMotivoAceptacion.setEditable(false);
        jTextMotivoAceptacion.setMaximumSize(new java.awt.Dimension(100, 20));
        jTextMotivoAceptacion.setMinimumSize(new java.awt.Dimension(100, 20));
        jTextMotivoAceptacion.setOpaque(false);
        jTextMotivoAceptacion.setPreferredSize(new java.awt.Dimension(100, 20));

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jTextSaldo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel1))
                    .add(jLabel2)
                    .add(jRadioButtonJugador)
                    .add(jRadioButtonObservador)
                    .add(jTextUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 153, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(68, 68, 68)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextMotivoAceptacion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 171, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel2)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextMotivoAceptacion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(15, 15, 15)
                        .add(jRadioButtonJugador)
                        .add(2, 2, 2)
                        .add(jRadioButtonObservador)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTextSaldo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel1)))
                    .add(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(84, 84, 84)
                .add(jButtonEstado)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 108, Short.MAX_VALUE)
                .add(jButtonSalida)
                .add(99, 99, 99))
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(11, 11, 11)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonEstado)
                    .add(jButtonSalida))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstadoActionPerformed
    
    EstadoCasino estadoCasino = new EstadoCasino(this.getVTerm(), this.getUsuario());
    XStream xstream1 = new XStream();

    xstream1.alias("estadoCasino", EstadoCasino.class);
    xstream1.useAttributeFor(EstadoCasino.class, "vTerm");
    xstream1.registerConverter(new VTermConverter());

    xstream1.useAttributeFor(EstadoCasino.class, "usuario");
    xstream1.registerConverter(new UsuarioConverter());


    String xml = xstream1.toXML(estadoCasino);
    xml = "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n" + xml;
    System.out.println(xml);   
    
    FileWriter file;
    try {
        file = new FileWriter("/Temp/Servidor/pedidoEstadoCasino" + this.getGrupo() + this.getVTerm().getId() + ".xml");
        file.write(xml);
        file.close();

    } catch (IOException ex) {
       Logger.getLogger(Entrada.class.getName()).log(Level.SEVERE, null, ex);
    } 
    
    // SE ENVIO PEDIDO, SE ESPERA RESPUESTA!!

    String archivo = "/Temp/respuestaEstadoCasino" + this.getGrupo() + this.getVTerm().getId() + ".xml";
    
    while (!(new File(archivo)).exists());
  
    StringBuffer buff = new StringBuffer();
    
    try {
        FileReader fileR = new FileReader(archivo);
    
        fileR.read();

        int c;
        while ((c = fileR.read()) != -1) {
            buff.append(Character.toChars(c)[0]);
        }
        
         fileR.close();
        
        while (!(new File(archivo)).delete());
        
    } catch (IOException ex) {
        
    }
    
    String xml2 = buff.toString();
    
    xml2 = xml2.substring(xml2.indexOf("?>") + 3);
    
    System.out.println(xml2);
    
       
    XStream xstream = new XStream(new DomDriver());
    xstream.alias("jugador", Jugador.class);
    xstream.alias("mesaCraps", MesaCraps.class);
    xstream.useAttributeFor(MesaCraps.class, "id");
    xstream.registerConverter(new IdConverter());
    xstream.registerConverter(new JugadorConverter());
    xstream.registerConverter(new ObservadorConverter());
    xstream.alias("observador", Observador.class);
    xstream.alias("jugador", Jugador.class);
    xstream.alias("craps", Craps.class);
    xstream.alias("tragamonedas", Tragamonedas.class);
    xstream.alias("juegos", Juego.class);
    xstream.alias("pozosCasino", PozosCasino.class);
    xstream.alias("estadoCasino", RespuestaEstadoCasino.class);
    xstream.useAttributeFor(RespuestaEstadoCasino.class, "vTerm");
    xstream.registerConverter(new VTermConverter());
    xstream.useAttributeFor(RespuestaEstadoCasino.class, "usuario");
    xstream.registerConverter(new UsuarioConverter());
    
    RespuestaEstadoCasino rta = (RespuestaEstadoCasino)xstream.fromXML(xml2);
    
    Iterator it = rta.getJugadores().iterator();
         
    // Iterador Jugadores           
    DefaultComboBoxModel lm = new DefaultComboBoxModel();
        
    while (it.hasNext()) {
        lm.addElement(it.next());
    }
    this.jListJugadores.setModel(lm);
    
    it = rta.getObservadores().iterator();
         
    // Iterador obs
    lm = new DefaultComboBoxModel();
        
    while (it.hasNext()) {
        lm.addElement(it.next());
    }
    this.jListObservadores.setModel(lm);
    
    this.setCraps(rta.getJuego().getCraps());
    this.setTraga(rta.getJuego().getTragamonedas());
    this.jTextPozoProgresivo.setText(rta.getJuego().getTragamonedas().getPozoProgresivo());
    
    it = this.getCraps().getMesasCraps().iterator();
         
    // Iterador obs
    lm = new DefaultComboBoxModel();
        
    while (it.hasNext()) {
        lm.addElement("Mesa " + ((MesaCraps)it.next()).getId());
    }
    this.jComboMesasCraps.setModel(lm);
    
}//GEN-LAST:event_jButtonEstadoActionPerformed

private void jButtonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalidaActionPerformed
    SalidaCasino salidaCasino = new SalidaCasino(this.getVTerm(), this.getUsuario());
    XStream xstream = new XStream();
    
    xstream.alias("salidaCasino", SalidaCasino.class);
    xstream.useAttributeFor(SalidaCasino.class, "vTerm");
    xstream.registerConverter(new VTermConverter());
    
    xstream.useAttributeFor(SalidaCasino.class, "usuario");
    xstream.registerConverter(new UsuarioConverter());

    String xml = xstream.toXML(salidaCasino);
    xml = "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n" + xml;
    System.out.println(xml);
    
        FileWriter file;
    try {
        file = new FileWriter("/Temp/Servidor/salidaCasino" + this.getGrupo() + this.getVTerm().getId() + ".xml");
        file.write(xml);
        file.close();

    } catch (IOException ex) {
       Logger.getLogger(Entrada.class.getName()).log(Level.SEVERE, null, ex);
    } 
    
    // SE ENVIO PEDIDO, SE ESPERA RESPUESTA!!
        
    String archivo = "/Temp/respuestaSalidaCasino" + this.getGrupo() + this.getVTerm().getId() + ".xml";
    
    while (!(new File(archivo)).exists());
  
    StringBuffer buff = new StringBuffer();
    
    try {
        FileReader fileR = new FileReader(archivo);
    
        fileR.read();

        int c;
        while ((c = fileR.read()) != -1) {
            buff.append(Character.toChars(c)[0]);
        }
        
         fileR.close();
        
        while (!(new File(archivo)).delete());
        
    } catch (IOException ex) {
        
    }
    
    String xml2 = buff.toString();
    
    xml2 = xml2.substring(xml2.indexOf("?>") + 3);
    
    System.out.println(xml2);
    
    XStream xstream1 = new XStream(new DomDriver());
    xstream1.alias("salidaCasino", RespuestaSalidaCasino.class);
    xstream1.useAttributeFor(RespuestaSalidaCasino.class, "vTerm");
    xstream1.registerConverter(new VTermConverter());
    xstream1.useAttributeFor(RespuestaSalidaCasino.class, "usuario");
    xstream1.registerConverter(new UsuarioConverter());
    RespuestaSalidaCasino e = (RespuestaSalidaCasino)xstream1.fromXML(xml2);
    
    if ("si".equals(e.getAceptado())) {
        this.setVisible(false);
    } else if ("no".equals(e.getAceptado())) {
        this.jTextMotivoAceptacion.setText(e.getDescripcion());
    }
}//GEN-LAST:event_jButtonSalidaActionPerformed

private void jRadioButtonJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJugadorActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jRadioButtonJugadorActionPerformed

private void jTextUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUsuarioActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextUsuarioActionPerformed

private void jButtonVerDetalleMesaTrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerDetalleMesaTrActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jButtonVerDetalleMesaTrActionPerformed

private void jComboMesasCrapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMesasCrapsActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jComboMesasCrapsActionPerformed

private void jButtonVerDetalleMesaCrapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerDetalleMesaCrapsActionPerformed

    VerMesaCraps mesa = new VerMesaCraps();
    
    Iterator it = this.getCraps().getMesasCraps().iterator();
    
    MesaCraps mesaCraps = null;
    while (it.hasNext()) {
        mesaCraps = (MesaCraps)it.next();
        if (("Mesa " + mesaCraps.getId()).equals(this.jComboMesasCraps.getSelectedItem()))
            break;
    }
    mesa.setJugadores(mesaCraps.getJugadores());
    mesa.setTiradorProximo(mesaCraps.getProximoTiro().getTirador());
    mesa.setSalida(("si".equals(mesaCraps.getProximoTiro().getTiroSalida()))?1:0);
    mesa.setPunto(mesaCraps.getProximoTiro().getPunto());
    mesa.setTiradorUltimoTiro(mesaCraps.getUltimoTiro().getTirador());
    mesa.setResultado(mesaCraps.getUltimoTiro().getResultado());
    mesa.setVisible(true);
     
}//GEN-LAST:event_jButtonVerDetalleMesaCrapsActionPerformed

private void jComboMesasTragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMesasTragaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jComboMesasTragaActionPerformed

    public JComboBox getJComboMesasCraps() {
        return jComboMesasCraps;
    }

    public void setJComboMesasCraps(JComboBox jComboMesasCraps) {
        this.jComboMesasCraps = jComboMesasCraps;
    }

    public JComboBox getJComboMesasTraga() {
        return jComboMesasTraga;
    }

    public void setJComboMesasTraga(JComboBox jComboMesasTraga) {
        this.jComboMesasTraga = jComboMesasTraga;
    }

    public JList getJListFichas() {
        return jListFichas;
    }

    public void setJListFichas(JList jListFichas) {
        this.jListFichas = jListFichas;
    }

    public JList getJListJugadores() {
        return jListJugadores;
    }

    public void setJListJugadores(JList jListJugadores) {
        this.jListJugadores = jListJugadores;
    }

    public JTextField getJTextMotivoAceptacion() {
        return jTextMotivoAceptacion;
    }

    public void setMotivoAceptacion(String motivo) {
        this.jTextMotivoAceptacion.setText(motivo);
    }

    public void setJTextPozoProgresivo(JTextField jTextPozoProgresivo) {
        this.jTextPozoProgresivo = jTextPozoProgresivo;
    }
    
    public void setModoIngreso(int modo) {
        if (modo == 1)
            this.jRadioButtonJugador.setSelected(true);
        else
            this.jRadioButtonObservador.setSelected(true);
    }

    public void setSaldo(String saldo) {
        this.jTextSaldo.setText(saldo);
    }

    public void setUsuario(String jTextUsuario) {
        this.jTextUsuario.setText(jTextUsuario);
    }
    
    // Mas variables
    private Craps craps;
    private Tragamonedas traga;
    private Usuario usuario;
    private List fichas;

    public void setFichas(List fichas) {
        Iterator it = fichas.iterator();
        // Iterador Jugadores           
        DefaultComboBoxModel lm = new DefaultComboBoxModel();
        while (it.hasNext()) {
            lm.addElement(it.next());
        }
        this.jListFichas.setModel(lm);        
    }

    public String getGrupo() {
        return grupo;
    }

    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public Vterm getVTerm() {
        return vTerm;
    }

    public void setVTerm(Vterm vTerm) {
        this.vTerm = vTerm;
    }
    private Vterm vTerm;
    private String grupo;

    public Tragamonedas getTraga() {
        return traga;
    }

    public void setTraga(Tragamonedas traga) {
        this.traga = traga;
    }

    public Craps getCraps() {
        return craps;
    }

    public void setCraps(Craps craps) {
        this.craps = craps;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEstado;
    private javax.swing.JButton jButtonSalida;
    private javax.swing.JButton jButtonVerDetalleMesaCraps;
    private javax.swing.JButton jButtonVerDetalleMesaTr;
    private javax.swing.JComboBox jComboMesasCraps;
    private javax.swing.JComboBox jComboMesasTraga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jListFichas;
    private javax.swing.JList jListJugadores;
    private javax.swing.JList jListObservadores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButtonJugador;
    private javax.swing.JRadioButton jRadioButtonObservador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextMotivoAceptacion;
    private javax.swing.JTextField jTextPozoProgresivo;
    private javax.swing.JTextField jTextSaldo;
    private javax.swing.JTextField jTextUsuario;
    // End of variables declaration//GEN-END:variables

}
